CREATE TABLE work_pattern_change_requests (
    request_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    break_minutes INT NOT NULL DEFAULT 0,
    working_minutes INT NOT NULL DEFAULT 0,
    reason VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    approved_by_employee_id BIGINT,
    approved_at DATETIME,
    rejected_by_employee_id BIGINT,
    rejected_at DATETIME,
    rejection_comment VARCHAR(500),
    apply_monday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_tuesday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_wednesday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_thursday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_friday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_saturday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_sunday BOOLEAN NOT NULL DEFAULT FALSE,
    apply_holiday BOOLEAN NOT NULL DEFAULT FALSE,
    INDEX idx_work_pattern_employee (employee_id),
    INDEX idx_work_pattern_status (status),
    INDEX idx_work_pattern_period (employee_id, start_date, end_date)
);
